/**
 * Re-derive every vehicle's fuel type from EPA's vehicles.csv and report (or
 * fix) records in cars.json that disagree.
 *
 * cars.json is generated by build-verified-database.ts, but regenerating it
 * needs network access to EPA and NHTSA and rewrites everything. When only the
 * fuel-type mapping changes, this applies that one correction in place.
 *
 * Usage:
 *   tsx scripts/reconcile-fuel-types.ts [--csv=path/to/vehicles.csv]          # report
 *   tsx scripts/reconcile-fuel-types.ts [--csv=path/to/vehicles.csv] --write  # fix cars.json
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { parse } from 'csv-parse/sync';
import type { Car } from '../src/types/car.types.js';
import { mapEpaFuelType, type EpaFuelFields } from './lib/epa-fuel-type.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = resolve(__dirname, '..', 'data');
const CARS_PATH = join(DATA_DIR, 'cars.json');

const args = process.argv.slice(2);
const csvPath =
  args.find((a) => a.startsWith('--csv='))?.slice('--csv='.length) ??
  join(DATA_DIR, 'raw', 'vehicles.csv');
const write = args.includes('--write');

const rows = parse(readFileSync(csvPath, 'utf8'), { columns: true, bom: true }) as Array<
  EpaFuelFields & { id: string }
>;
const byEpaId = new Map(rows.map((row) => [row.id, row]));

const db = JSON.parse(readFileSync(CARS_PATH, 'utf8')) as { cars: Car[] };
const changes = new Map<string, string[]>();
let unmatched = 0;

for (const car of db.cars) {
  const row = car.epaId != null ? byEpaId.get(String(car.epaId)) : undefined;
  if (!row) {
    unmatched++;
    continue;
  }
  const epaFuel = mapEpaFuelType(row);
  if (epaFuel === car.engine.fuelType) continue;
  const key = `${car.engine.fuelType} -> ${epaFuel}`;
  changes.set(key, [...(changes.get(key) ?? []), car.id]);
  if (write) car.engine = { ...car.engine, fuelType: epaFuel };
}

const total = [...changes.values()].reduce((n, ids) => n + ids.length, 0);
console.log(
  `${db.cars.length.toLocaleString()} cars, ${unmatched} without an EPA row, ${total} disagree with EPA.`,
);
for (const [key, ids] of changes) {
  console.log(`\n${key} (${ids.length})`);
  for (const id of ids) console.log(`  ${id}`);
}

if (write && total > 0) {
  writeFileSync(CARS_PATH, JSON.stringify(db));
  console.log(`\nUpdated ${CARS_PATH}. Run build-runtime-db to rebuild cars-ready.json.`);
}
